# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180209_1307'),
    ]

    operations = [

    ]
