# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180207_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
